name: Run Twitter Bot

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # allow manual run from GitHub Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Run the bot
      - name: Run twitter_bot.py
        env:
          TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
          TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
          TWITTER_REFRESH_TOKEN: ${{ secrets.TWITTER_REFRESH_TOKEN }}
        run: |
          python twitter_bot.py
